services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8001:5000
    networks:
      - shared_network
    volumes:
      - .:/app

    depends_on:
      - db
  
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    networks:
      - shared_network
    depends_on:
      - db

  db:
    image: mysql:8.0.39
    restart: always
    environment:
      MYSQL_PORT: 3306
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
    networks:
      - shared_network

networks:
  shared_network:
    external: true
    driver: bridge
